#undef TAPPING_TERM
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY

#define ONESHOT_TAP_TOGGLE 2
#define TAPPING_TOGGLE 1

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1000

#define PERMISSIVE_HOLD

#define COMBO_TERM 75

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 500

//#define MK_COMBINED
//#define MOUSEKEY_DELAY 0
//#define MOUSEKEY_MAX_SPEED 7
//#define MOUSEKEY_TIME_TO_MAX 45
//#define MOUSEKEY_WHEEL_DELAY 100
//#define MOUSEKEY_WHEEL_MAX_SPEED 10
#define MK_KINETIC_SPEED
#define MOUSEKEY_MOVE_DELTA 32
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 8
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 48

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 200

#define CAPS_WORD_INVERT_ON_SHIFT
